name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          # If you have a requirements file, install it; ignore missing file
          [ -f requirements.txt ] && pip install -r requirements.txt || true
          # Local package (if you have a setup.cfg/pyproject)
          pip install -e . || true
          # Test tools
          pip install pytest

      - name: Set demo/offline env so tests don't call external APIs
        run: |
          echo "OFFLINE_REC_FALLBACK=1" >> $GITHUB_ENV
          echo "UNIVERSE_LIMIT=20" >> $GITHUB_ENV
          echo "AV_MAX_CALLS_PER_RUN=5" >> $GITHUB_ENV
          echo "LLM_PROVIDER=anthropic" >> $GITHUB_ENV
          echo "ANTHROPIC_API_KEY=dummy" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=dummy" >> $GITHUB_ENV
          echo "GEMINI_API_KEY=dummy" >> $GITHUB_ENV
          echo "GOOGLE_CLOUD_PROJECT=riskvaluesagent" >> $GITHUB_ENV
          echo "GOOGLE_CLOUD_LOCATION=us-central1" >> $GITHUB_ENV
          echo "VERTEX_MODEL=gemini-2.0-flash" >> $GITHUB_ENV

      - name: Smoke import (no network)
        run: |
          python - <<'PY'
          import importlib
          mods = [
            "agent.models",
            "agent.mission",
            "agent.tools",
            "agent.planner",
          ]
          for m in mods:
            importlib.import_module(m)
            print("Imported:", m)
          print("Smoke import OK")
          PY

      - name: Run unit tests
        run: pytest -q --disable-warnings --maxfail=1
